/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author robal
 */
public class General extends javax.swing.JFrame {

    /**
     * Creates new form Secante
     */
    public General() {
        initComponents();
        this.setLocationRelativeTo(null);
        ver(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jtbTabal = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        btnSecante = new javax.swing.JButton();
        btnFerra = new javax.swing.JButton();
        btnTart = new javax.swing.JButton();
        btnHor = new javax.swing.JButton();
        btnMuller = new javax.swing.JButton();
        cmbSelect = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtRaiz = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtError = new javax.swing.JTextField();
        btnBairs = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setName("METODOS "); // NOI18N

        jtbTabal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtbTabal);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 830, 230));

        jButton1.setText("Regresar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 460, -1, -1));

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/_active__no.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 40, 30));

        btnSecante.setText("Metodo Secante");
        btnSecante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSecanteActionPerformed(evt);
            }
        });
        getContentPane().add(btnSecante, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        btnFerra.setText("Metodo Ferrari");
        btnFerra.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                btnFerraItemStateChanged(evt);
            }
        });
        btnFerra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFerraActionPerformed(evt);
            }
        });
        getContentPane().add(btnFerra, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, -1, -1));

        btnTart.setText("Metodo Tartalia");
        btnTart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTartActionPerformed(evt);
            }
        });
        getContentPane().add(btnTart, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, -1, -1));

        btnHor.setText("Metodo Horner");
        btnHor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHorActionPerformed(evt);
            }
        });
        getContentPane().add(btnHor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 40, -1, -1));

        btnMuller.setText("Metodo Müller");
        btnMuller.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMullerActionPerformed(evt);
            }
        });
        getContentPane().add(btnMuller, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, -1, -1));

        cmbSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "--Selecione una ecuacion--", "e^(x-1) -1.5x=0", "2senx=x", "e^x - 4 = 0", "e^-(x-1)*sen(x) = 1", "4sen(x) = e^x" }));
        cmbSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSelectItemStateChanged(evt);
            }
        });
        cmbSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectActionPerformed(evt);
            }
        });
        getContentPane().add(cmbSelect, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 250, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("F(x)=");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 30, 30));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("RAIZ: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 40, -1));
        getContentPane().add(txtRaiz, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 160, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ERROR: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 110, -1, -1));
        getContentPane().add(txtError, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 190, -1));

        btnBairs.setText("Metodo Bairstow");
        btnBairs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBairsActionPerformed(evt);
            }
        });
        getContentPane().add(btnBairs, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 40, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/fondo-gris.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 490));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnSecanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSecanteActionPerformed
        Oculta();
        ver(true);
    }//GEN-LAST:event_btnSecanteActionPerformed

    private void btnFerraItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_btnFerraItemStateChanged
        Oculta();
        ver(true);
    }//GEN-LAST:event_btnFerraItemStateChanged

    private void btnFerraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFerraActionPerformed
        Oculta();
        ver(true);    }//GEN-LAST:event_btnFerraActionPerformed

    private void btnTartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTartActionPerformed
        Oculta();
        ver(true);
    }//GEN-LAST:event_btnTartActionPerformed

    private void btnHorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHorActionPerformed
        Oculta();
        ver(true);    }//GEN-LAST:event_btnHorActionPerformed

    private void btnMullerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMullerActionPerformed
        Oculta();
        ver(true);    }//GEN-LAST:event_btnMullerActionPerformed

    private void cmbSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSelectItemStateChanged
    }//GEN-LAST:event_cmbSelectItemStateChanged

    private void btnBairsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBairsActionPerformed
        Oculta();
        ver(true);
    }//GEN-LAST:event_btnBairsActionPerformed

    private void cmbSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectActionPerformed

    }//GEN-LAST:event_cmbSelectActionPerformed
    public void ver(boolean i) {
        cmbSelect.setVisible(i);
        txtError.setVisible(i);
        txtRaiz.setVisible(i);
        jLabel1.setVisible(i);
        jLabel4.setVisible(i);
        jScrollPane1.setVisible(i);
        jLabel3.setVisible(i);

    }
    public void Oculta() {
        btnBairs.setVisible(false);
        btnFerra.setVisible(false);
        btnHor.setVisible(false);
        btnMuller.setVisible(false);
        btnSecante.setVisible(false);
        btnTart.setVisible(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(General.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new General().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBairs;
    private javax.swing.JButton btnFerra;
    private javax.swing.JButton btnHor;
    private javax.swing.JButton btnMuller;
    private javax.swing.JButton btnSecante;
    private javax.swing.JButton btnTart;
    private javax.swing.JComboBox cmbSelect;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jtbTabal;
    private javax.swing.JTextField txtError;
    private javax.swing.JTextField txtRaiz;
    // End of variables declaration//GEN-END:variables
}
